### ISSUE TITLE
Plato.inspect broken

### ISSUE THREAD

**Issue by ilanbiala** [es-analysis/plato#136]
Snippet:
```
plato.inspect([
	'app/**/*.js',
	'config/**/*.js',
	'public/modules/**/*.js'
],
'report',
{
	jshint: {},
	complexity: {
		trycatch: true
	}
});
```
Error:
```
fs.js:438
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^
Error: ENOENT, no such file or directory 'app/**/*.js'
    at Object.fs.openSync (fs.js:438:18)
    at Object.fs.openSync (node_modules/plato/node_modules/fs-extra/node_modules/rimraf/node_modules/graceful-fs/graceful-fs.js:68:26)
    at Object.fs.readFileSync (fs.js:289:15)
    at node_modules/plato/lib/plato.js:86:25
    at Array.forEach (native)
    at runReports (node_modules/plato/lib/plato.js:73:11)
    at node_modules/plato/lib/plato.js:140:7
    at node_modules/plato/node_modules/fs-extra/node_modules/mkdirp/index.js:38:26
    at Object.oncomplete (fs.js:107:15)
```

**Comment by ilanbiala** [comment]
Yeah @jsoverson I think the issue is on line 48, because an array of globs should also work. We should probably change it to this:
```
function isString(obj) {
  return typeof obj === 'string' || obj instanceof String;
}

if (Array.isArray(files)) {
  if (isString(files[0])) {
    // array of globs
    files = files.map(glob.sync);
  } else {
    // files already given
    // do nothing
  }
} else if (isString(files)) {
  // single glob
  files = glob.sync(files);
}
```

Also, what is the function below supposed to do?
```
function unary(fn) { return function(a){ return fn(a);}; }
```

**Comment by ilanbiala** [comment]
@jsoverson Any thoughts on ^^?

**Comment by ilanbiala** [comment]
@jsoverson can you enlighten me on what's going on exactly with this code, because it seems a little confusing and weird.

**Comment by ilanbiala** [comment]
@jsoverson is another contributor going to be added because it seems you haven't been too active as of late.

**Comment by jsoverson** [comment]
@ilanbiala if you would be interested, feel free to submit pull requests and I'll add you after you've shown ability to support. 

I've added many people who have expressed interest but haven't committed anything.

**Comment by ilanbiala** [comment]
I'm not saying it has to be me, but this project should be continued if not by you by someone who can improve it.

**Comment by jsoverson** [comment]
I would love a contributor that is actively invested in daily use of plato and moving it forward. I've found it hard to find people interested in language analysis and reporting of metrics.

I'm still romantic about the idea of pushing out plato v2, but can't ignore my track record on the project as of late.

If you're interested, I can give you access. You have a record of contributing to other projects so if plato is something you're using then it certainly can't hurt.

**Comment by ilanbiala** [comment]
plato.inspect actually works just fine with the files passed in, I must have had a typo or a missing parameter before.

@jsoverson The biggest thing I'm interested in is persistent analysis through a database. Is there a particular one that you chose that I can start putting together a PR for?
