### ISSUE TITLE
Future of Plato discussion (2.0, roadmap, contributors)

### ISSUE THREAD

**Issue by jsoverson** [es-analysis/plato#138]
Hi watchers and other interested parties.

Plato has become more popular than I anticipated and now needs new blood on the team to keep it moving forward. Since this project's inception I've changed jobs twice and am no longer in a position where the reports are relevant on a regular basis so am finding it difficult to stay up to date with issues and progress.

There was substantial work done on a [2.0 branch](https://github.com/es-analysis/plato/tree/v2.0.0-wip) almost 12 months ago but it was unable to get out the door for a variety of reasons. The previous goals for 2.0 were:
- utilize a local database for reports/history
- rewrite the web app 
- modularize visual components (to make it easier to accept charting/viz contributions)
- modularize reporting components (to make it easier to support coffeescript, eslint, etc)
- _edit_ record configuration in a .plato.rc

These still seem relevant but that's what this discussion is for. How are people using plato now? What are the biggest pain points? Who is using plato actively and is interested in contributing to the future?

My [current position](https://github.com/shapesecurity) has renewed my ability to focus on JavaScript tooling, but Plato itself isn't in use regularly due to the scope of internal projects. This leaves me in a good position to contribute to parts of Plato but not necessarily to lead overall direction and understand user's needs. 

All thoughts welcome!

cc @there4

**Comment by ilanbiala** [comment]
It would probably make sense to release each part separately as a 1.x release if possible, no?

**Comment by jsoverson** [comment]
If possible. When first worked on the lot of it was grouped together because it seemed attainable in short order and contained many breaking changes.

Going forward, most of the changes are probably implementable in small chunks

**Comment by ilanbiala** [comment]
Is anything fully working or is everything a WIP? I think most people will appreciate DB and visualization support first.

**Comment by jsoverson** [comment]
@ilanbiala the focus was the foundation and the modularity of the reporters in the 2.0 branch. There was some effort to complete the frontend, but I no longer think the approach being taken was the best.

Thoughts welcome on how to best approach modular visual components that may take data in from various reporters.

**Comment by ilanbiala** [comment]
What are all the possible metrics just so we know what is being displayed?

**Comment by mindmelting** [comment]
Having reporters as seperate npm modules would be neat.

**Comment by jsoverson** [comment]
@ilanbiala thanks for your contributions lately, would you be open to being added as a contributor?

**Comment by ilanbiala** [comment]
@jsoverson I think for now it may be easier if you give me a couple things and I'll submit them through PRs first just so I get more familiar with the code and have someone to review it.

**Comment by ilanbiala** [comment]
Any suggestions on little things I should start working on?

**Comment by ctumolosus** [comment]
Would be nice to have the ability to generate static analysis using popular tools such as: JSLint, JSHint, ESLint, and JSCS. Should be able to choose multiple of them.

**Comment by xavhan** [comment]
Generating report by folder would be great, always seeing all files is most of the time not really relevant.

**Comment by DNR500** [comment]
Love Plato. Find it to be an incredibly useful tool. Probably completely off topic however what about visualisation for css/scss metrics?
