### ISSUE TITLE
ES6 support - use espree?

### ISSUE THREAD

**Issue by matchdav** [es-analysis/plato#173]
I'd like to be using this on ES6 code.  Is this on the roadmap?  Need help?

**Comment by jsoverson** [comment]
It's not a matter of the parser, esprima parses es6. Escomplex has stopped being maintained.

I have complexity analysis complete (pending a couple bugs) via the shift parser. Plato v2 is done except for the dashboard, though there is a console and json reporter. Maybe it would be worthwhile to put plato v2 up with just the minimal reporters and get help on the dashboard module.

I'll graft the rewrite onto the original, and start pushing repositories up soon.
