### ISSUE TITLE
Plato for ES2015

### ISSUE THREAD

**Issue by dazlious** [es-analysis/plato#180]
Will there be an update soon for using plato with es_2015 syntax?

For now I am transpiling all files to es5 with babel-loader (es_2015) and then running the analysis.

My main problem is, that my code's complexity is higher than normal and jshint/lint isn't working well, because babel transpiles it other not the way I wrote it ;)

I know of this fork: https://github.com/peterkc/es6-plato 
But that does not work correctly

**Comment by jsoverson** [comment]
I don't know, and I know that answer sucks. Escomplex, which plato relies on, transferred ownership some time ago and the current state of its es2015 support isn't stable enough to rely on. I've made a new [complexity analysis library](https://github.com/jsoverson/shift-complexity) based off the shift parser which supports es2015 but isn't a drop in replacement for a lot of reasons.

**Comment by dazlious** [comment]
Ah okay, looking forward to it ;)
If you need help or testing, you can contact me. Love to see your results
