### ISSUE TITLE
Example of how to combine with babel for ES6 module imports

### ISSUE THREAD

**Issue by danielsneijers** [es-analysis/plato#194]
I love the fact that you support es6 now, but I can't get plato to work with the es6 style module imports. With mocha for example I can use an argument like `--compilers js:babel-register`, but I can't figure out how to make plate work with something like babel-register. Any help is greatly appreciated.

**Comment by typhonrt** [comment]
The message in the repo README about ES6 support was preemptive as what it really means is that Plato doesn't crash when ES6 classes are encountered. No stat generation occurs for ES6+ code. I have a PR #192 that is waiting for a merge which brings actual ES6+ support to Plato. Plato itself is ES5 / CJS, so there is nothing about itself or the subsequent runtime that necessitates Babel. 

You can give ES6 support a try early by installing a fork from Github which is described in #193

**Comment by danielsneijers** [comment]
Thanks a lot man, works like a charm!
