### ISSUE TITLE
dynamic import causes SyntaxError: Unexpected token (37:30)

### ISSUE THREAD

**Issue by mauricionr** [es-analysis/plato#214]
I'm using Vue 2.x.x  with webpack 4.x.x and also dynamic import

here's the snippet in the line 37:30 

```javascript
export default new Vue({
...
components: {
    'simple-promotion': () => import(//37:30
      /* webpackChunkName: "simple-promotion" */
      '../../components/simplePromotion.vue'
    ),
 }
...
})
```

**Comment by typhonrt** [comment]
Hi @mauricionr I'm the author of the underlying complexity reporting module, [typhonjs-escomplex](https://www.npmjs.com/package/typhonjs-escomplex) that Plato uses. I just have published a new version which has switched to [Babel parser](https://babeljs.io/docs/en/next/babel-parser.html) and have verified that a whole lot of edge JS and proposals are supported including the above. 

I'll be submitting a PR to Plato after I have integrated the new version in the next day or so. 

Even cooler is that Typescript will work now too! 🎉
