### ISSUE TITLE
Could not parse JSON from file /{PATH}/report.history.json

### ISSUE THREAD

**Issue by jstrimpel** [es-analysis/plato#37]
I am not sure if I am doing something incorrectly or if this is a known issue...

The reports are being generated correctly, but I am seeing the following warnings for each file. The paths are correct and the JSON files exist.

I am loading the plato task in another grunt plugin - not sure if that is pertinent.

Could not parse JSON from file /Users/jstrimp/castle-example/reports/analyze/files/a_js/report.history.json
Could not parse JSON from file /Users/jstrimp/castle-example/reports/analyze/files/x_js/report.history.json
Could not parse JSON from file /Users/jstrimp/castle-example/reports/analyze/files/y_js/report.history.json
Could not parse JSON from file /Users/jstrimp/castle-example/reports/analyze/report.history.json

**Comment by saas786** [comment]
+1,

Annoying, caused me to think its an error. 
@jsoverson like he said, it will not show up second time but still not a good thing. Better message will be appreciated.
