### ISSUE TITLE
I get a lot of 'Could not parse JSON' errors

### ISSUE THREAD

**Issue by RobertGary1** [es-analysis/plato#42]
I seem to get a good report (awesome!) but I do get a lot of errors...
Could not parse JSON from file report\files\commonComponents_tabPanelMain_demo_v
iew_DemoPanel_js\report.history.json
Could not parse JSON from file report\files\commonComponents_tabPanelMain_demo_v
iew_DemoToolbar_js\report.history.json
Could not parse JSON from file report\files\commonComponents_tabPanelMain_view_M
ainTabPanel_js\report.history.json
Could not parse JSON from file report\files\commonComponents_tabPanelMain_view_T
abPanelToolbar_js\report.history.json
Could not parse JSON from file report\files\commonComponents_tree_demo_app_model
_HardwareTreeGridModel_js\report.history.json
Could not parse JSON from file report\files\commonComponents_tree_demo_app_model
_HardwareTreeModel_js\report.history.json
Could not parse JSON from file report\files\commonComponents_tree_demo_app_store
_HardwareTreeGridStore_js\report.history.json
Could not parse JSON from file report\files\commonComponents_tree_demo_app_store
_HardwareTreeStore_js\report.history.json
Could not parse JSON from file report\files\commonComponents_tree_demo_app_view_
TreeDemoTabPanel_js\report.history.json
Could not parse JSON from file report\files\commonComponents_tree_demo_app_view_
Viewport_js\report.history.json
Could not parse JSON from file report\files\commonComponents_tree_demo_app_js\re
port.history.json
Could not parse JSON from file report\files\commonComponents_underlinedPanel_dem
o_app_js\report.history.json
Could not parse JSON from file report\files\commonComponents_underlinedPanel_Und
erlinedPanel_js\report.history.json
Could not parse JSON from file report\files\commonComponents_wizard_controller_W
izardController_js\report.history.json
Could not parse JSON from file report\files\commonComponents_wizard_demo_demo_js
\report.history.json
Could not parse JSON from file report\files\commonComponents_wizard_view_private
_WizardContentPane_js\report.history.json
Could not parse JSON from file report\files\commonComponents_wizard_view_private
_WizardHelpWindow_js\report.history.json
Could not parse JSON from file report\files\commonComponents_wizard_view_private
_WizardNavigation_js\report.history.json
Could not parse JSON from file report\files\commonComponents_wizard_view_private
_WizardStepsPane_js\report.history.json
Could not parse JSON from file report\files\commonComponents_wizard_view_Wizard_
js\report.history.json
Could not parse JSON from file report\files\commonComponents_wizard_view_WizardP
age_js\report.history.json
Could not parse JSON from file report\report.history.json
Done!

**Comment by varemenos** [comment]
+1, it's really poor experience

**Comment by andre-ferreira-qlik** [comment]
On each build we append the plato reports, its quite annoying to have people ask me about the message every time. Can and will you address this?
