### ISSUE TITLE
Code duplication analysis

### ISSUE THREAD

**Issue by Floby** [es-analysis/plato#76]
Hello,

I'm using Plato as part of my CI chain extensively. It has been of great help so far. There are only two features missing for our use case and one is the subject of my question.

Are there any plans to include a code duplication detection feature to Plato's reports ?

Thank you very much.

PS: the second feature we miss is code coverage reports, but that part is covered by Istanbul for now.

**Comment by Chris2011** [comment]
How is the progress for v2? As I understand it right, copy and paste detection is already implemented in v2, or? It would be very nice to see this feature, so I don't need to use an 3rd party tool like JSCPD.
